name: Minimal Release v1.0.0

on:
  workflow_dispatch:
  push:
    tags:
      - 'v1.0.0'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore
      run: dotnet restore

    - name: Build without analyzers
      run: |
        # Build without running analyzers to avoid analyzer issues
        dotnet build -c Release --no-restore /p:RunAnalyzers=false /p:RunAnalyzersDuringBuild=false

    - name: Pack NuGet packages
      run: |
        # Pack without building again
        dotnet pack -c Release --no-build -o ./nupkgs /p:RunAnalyzers=false
        
        echo "=== Packages created ==="
        ls -la ./nupkgs/*.nupkg | grep -v snupkg || echo "No packages found"
        echo "Total packages: $(ls ./nupkgs/*.nupkg 2>/dev/null | grep -v snupkg | wc -l)"

    - name: Publish essential R3E packages only
      env:
        NUGET_API_KEY: ${{ secrets.NUGET }}
      run: |
        # Publish only the most essential R3E packages first
        ESSENTIAL_PACKAGES=(
          "R3E.SmartContract.Framework"
          "R3E.Compiler.CSharp.Tool"
          "R3E.SmartContract.Testing"
          "R3E.SmartContract.Deploy"
        )
        
        for PKG in "${ESSENTIAL_PACKAGES[@]}"; do
          PACKAGE=$(ls ./nupkgs/${PKG}.*.nupkg 2>/dev/null | grep -v snupkg | head -1)
          if [ -n "$PACKAGE" ]; then
            echo "Publishing $(basename $PACKAGE)..."
            dotnet nuget push "$PACKAGE" \
              --source https://api.nuget.org/v3/index.json \
              --api-key "$NUGET_API_KEY" \
              --skip-duplicate \
              --timeout 600 || echo "Failed or already exists: $(basename $PACKAGE)"
          fi
        done

    - name: Create simple release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./nupkgs/R3E.Compiler.CSharp.Tool.*.nupkg
          ./nupkgs/R3E.SmartContract.Framework.*.nupkg
        body: |
          # R3E DevPack v1.0.0
          
          First major release of R3E DevPack.
          
          ## Installation
          ```bash
          dotnet tool install -g R3E.Compiler.CSharp.Tool --version 1.0.0
          ```
          
          See full documentation for details.
        name: R3E DevPack v1.0.0
        draft: false
        prerelease: false
        fail_on_unmatched_files: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}