name: Release v1.0.0 (Skip Tests)

on:
  workflow_dispatch:
  push:
    tags:
      - 'v1.0.0'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Build
      run: |
        echo "Building solution..."
        make build
        echo "Build completed successfully!"

    - name: Pack
      run: |
        echo "Packing NuGet packages..."
        make pack
        echo "Packages created:"
        ls -la artifacts/*.nupkg | grep -v snupkg || echo "No packages found"

    - name: Build Linux binary
      run: |
        dotnet publish src/Neo.Compiler.CSharp.Tool/Neo.Compiler.CSharp.Tool.csproj \
          -c Release \
          -r linux-x64 \
          --self-contained true \
          /p:PublishSingleFile=true \
          /p:PublishTrimmed=false \
          -o ./publish/linux-x64
        
        cd publish/linux-x64
        chmod +x rncc
        tar -czf ../../rncc-linux-x64-v1.0.0.tar.gz rncc
        cd ../..

    - name: Publish to NuGet
      env:
        NUGET_API_KEY: ${{ secrets.NUGET }}
      run: |
        echo "Publishing packages to NuGet..."
        
        # Publish R3E packages
        for package in ./artifacts/R3E*.nupkg; do
          if [[ -f "$package" && ! "$package" =~ \.snupkg$ ]]; then
            echo "Publishing $(basename $package)..."
            dotnet nuget push "$package" \
              --source https://api.nuget.org/v3/index.json \
              --api-key "$NUGET_API_KEY" \
              --skip-duplicate \
              --timeout 600 || echo "Failed or already exists: $(basename $package)"
          fi
        done
        
        # Publish Neo packages
        for package in ./artifacts/Neo*.nupkg; do
          if [[ -f "$package" && ! "$package" =~ \.snupkg$ ]]; then
            echo "Publishing $(basename $package)..."
            dotnet nuget push "$package" \
              --source https://api.nuget.org/v3/index.json \
              --api-key "$NUGET_API_KEY" \
              --skip-duplicate \
              --timeout 600 || echo "Failed or already exists: $(basename $package)"
          fi
        done

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./artifacts/*.nupkg
          rncc-linux-x64-v1.0.0.tar.gz
          RELEASE_NOTES_v1.0.0.md
          CHANGELOG.md
          QUICK_START_v1.0.0.md
          MIGRATION_GUIDE_v1.0.0.md
        body_path: RELEASE_NOTES_v1.0.0.md
        name: R3E DevPack v1.0.0 - First Major Release
        draft: false
        prerelease: false
        fail_on_unmatched_files: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}